# This is a basic workflow to help you get started with Actions

name: Jobs_Scraping_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push event 
  push:
    branches: [ dev,prod ]
    tags:
      - 'v*.*.*'
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  python-build:
#     if: ${{ github.event_name == 'workflow_dispatch' }}       # Run only if triggered manually
    runs-on: ubuntu-latest
#     container: python:3.8-alpine  # same as the one on the dockerfile
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Create env file
        run: |
          touch .env
          echo HEADERS=${{secrets.HEADERS}} >> .env
          echo PASSWORD=${{ secrets.PASSWORD }} >> .env
          echo PROXY=${{ secrets.PROXY }} >> .env
          echo RECEIVER_EMAIL=${{ secrets.RECEIVER_EMAIL }} >> .env
          echo SENDER_EMAIL=${{ secrets.SENDER_EMAIL }} >> .env
          echo pwd
          cat .env
          
      - name: Set up QEMU        
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx        
        uses: docker/setup-buildx-action@v1  
        
#       - name: docker build job_scrapy_app
#         run: |
#           docker buildx build -t  --platform=linux/arm64,linux/amd64 kyien/job_scraping:v1.0.0 .
          
        # login to docker hub
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Docker meta for PMS
        id: meta_js
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
             kyien/job_scraping
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_js.outputs.tags }}
          labels: ${{ steps.meta_js.outputs.labels }} 
          
      - name: Docker Hub Description
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: kyien/job_scraping
          readme-filepath: ./README.md
          short-description: "Jobs scraping image for python automation"
    
    
      
    
